

# stores the heroes stats
# make sure to replace any - with a space in the heroes name
# hp, atk, armour and speed are what is shown of the 10*s in the pokedex
# other stats e.g. skill damage are whats said in the stat buff passive,
# percent atk/hp/armour e.g. +30% hp are stored under the name "hp_mult"/"atk_mult"/"armour_mult"
# +speed in the passive is ignored since it is already added to the pokedex stats

HERO_STATS = {
    'betty': {
        'class': 'mage',
        'faction': 'shadow',
        'hp': 42307,
        'atk': 29606,
        'armour': 1631,
        'speed': 1173,
        'atk_mult': 20,
        'crit damage': 28,
        'damage reduction': 16},
    'azrael': {
        'class': 'assassin',
        'faction': 'shadow',
        'hp': 702919,
        'atk': 36691,
        'armour': 1607,
        'speed': 1212,
        'hp_mult': 35,
        'atk_mult': 35,
        'crit': 20,
        'control immunity': 25},
    'annabelle': {
        'class': 'priest',
        'faction': 'shadow',
        'hp': 698961,
        'atk': 21481,
        'armour': 1631,
        'speed': 1178,
        'hp_mult': 30,
        'damage reduction': 24,
        'control immunity': 24},
    'onkirimaru': {
        'class': 'warrior',
        'faction': 'shadow',
        'hp': 666254,
        'atk': 25777,
        'armour': 1631,
        'speed': 1172,
        'hp_mult': 30,
        'atk_mult': 20,
        'crit': 30,
        'armour break': 50,
        'damage reduction': 30},
    'eloise': {
        'class': 'ranger',
        'faction': 'shadow',
        'hp': 618664,
        'atk': 27145,
        'armour': 1631,
        'speed': 1188,
        'atk_mult': 20,
        'hp_mult': 30,
        'block': 60,
        'control immunity': 30},
    'tix': {
        'class': 'mage',
        'faction': 'shadow',
        'hp': 583614,
        'atk': 24672,
        'armour': 1631,
        'speed': 1218,
        'hp_mult': 35,
        'crit': 30,
        'control immunity': 30},
    'ithaqua': {
        'class': 'assassin',
        'faction': 'shadow',
        'hp': 537663,
        'atk': 36768,
        'armour': 1605,
        'speed': 1232,
        'atk_mult': 35,
        'crit': 35,
        'crit damage': 50,
        'control immunity': 30},
    'gustin': {
        'class': 'priest',
        'faction': 'shadow',
        'hp': 587747,
        'atk': 19544,
        'armour': 1605,
        'speed': 1178,
        'hp_mult': 25,
        'control immunity': 30,
        'effect of being healed': 30},
    'horus': {
        'class': 'warrior',
        'faction': 'shadow',
        'hp': 658277,
        'atk': 25407,
        'armour': 1605,
        'speed': 1160,
        'hp_mult': 40,
        'atk_mult': 30,
        'armour break': 40,
        'block': 60},
    'jahra': {
        'class': 'mage',
        'faction': 'shadow',
        'hp': 506052,
        'atk': 29743,
        'armour': 1554,
        'speed': 1188,
        'atk_mult': 20,
        'crit': 30,
        'hp_mult': 25,
        'damage against petrified': 60,
        'damage against stunned': 60},
    'kamath': {
        'class': 'ranger',
        'faction': 'shadow',
        'hp': 506123,
        'atk': 30307,
        'armour': 1802,
        'speed': 1161,
        'atk_mult': 35,
        'hp_mult': 25,
        'armour_mult': 20, # could be used for monsters
        'petrify immunity': 1},
    'corpsedemon': {
        'class': 'warrior',
        'faction': 'shadow',
        'hp': 808648,
        'atk': 15156,
        'armour': 1502,
        'speed': 1158,
        'block': 35,
        'hp_mult': 40,
        'freeze immunity': 1},
    'blood blade': {
        'class': 'assassin',
        'faction': 'shadow',
        'hp': 448961,
        'atk': 28893,
        'armour': 1476,
        'speed': 1172,
        'precision': 50,
        'atk_mult': 30,
        'armour break': 32,
        'hp_mult': 30,
        'damage against bleeding': 140},
    'walter': {
        'class': 'assassin',
        'faction': 'shadow',
        'hp': 466879,
        'atk': 30757,
        'armour': 1476,
        'speed': 1169,
        'armour break': 20,
        'atk_mult': 35,
        'hp_mult': 15,
        'damage against poison': 20},
    'field': {
        'class': 'ranger',
        'faction': 'shadow',
        'hp': 445469,
        'atk': 25371,
        'armour': 1476,
        'speed': 1140,
        'armour break': 40,
        'atk_mult': 35},
    'kharma': {
        'class': 'priest',
        'faction': 'shadow',
        'hp': 543384,
        'atk': 34694,
        'armour': 1424,
        'speed': 1144,
        'precision': 100,
        'atk_mult': 45,
        'hp_mult': 20,
        'damage against petrified': 100},
    'aidan': {
        'class': 'mage',
        'faction': 'shadow',
        'hp': 461851,
        'atk': 32147,
        'armour': 1424,
        'speed': 1126,
        'damage reduction': 24,
        'hp_mult': 30,
        'atk_mult': 30},
    'baade': {
        'class': 'warrior',
        'faction': 'shadow',
        'hp': 702072,
        'atk': 20655,
        'armour': 1554,
        'speed': 1155,
        'hp_mult': 40,
        'atk_mult': 25,
        'armour break': 50},
    'lutz': {
        'class': 'assassin',
        'faction': 'shadow',
        'hp': 464258,
        'atk': 27771,
        'armour': 1476,
        'speed': 1166,
        'armour break': 40,
        'atk_mult': 25,
        'hp_mult': 15},
    'dominator': {
        'class': 'warrior',
        'faction': 'shadow',
        'hp': 817980,
        'atk': 13846,
        'armour': 1502,
        'speed': 1152,
        'hp_mult': 40,
        'precision': 20},
    'aylamak': {
        'class': 'warrior',
        'faction': 'fortress',
        'hp': 699999,
        'atk': 27528,
        'armour': 2198,
        'speed': 1193,
        'hp_mult': 35,
        'atk_mult': 22,
        'block': 30,
        'damage reduction': 20,
        'damage against bleeding': 35},
    'holmes young': {
        'banned': True,
        'class': 'mage',
        'faction': 'fortress',
        'hp': 602517,
        'atk': 29557,
        'armour': 1554,
        'speed': 1238,
        'hp_mult': 30,
        'damage reduction': 25,
        'control immunity': 15,
        'atk_mult': 25},
    'saja': {
        'class': 'assassin',
        'faction': 'fortress',
        'hp': 618664,
        'atk': 32705,
        'armour': 1554,
        'speed': 1232,
        'hp_mult': 30,
        'atk_mult': 40,
        'crit': 30,
        'control immunity': 30},
    'fiona': {
        'class': 'priest',
        'faction': 'fortress',
        'hp': 666254,
        'atk': 25355,
        'armour': 1554,
        'speed': 1172,
        'atk_mult': 25,
        'hp_mult': 40,
        'crit': 30,
        'precision': 50},
    'inosuke': {
        'class': 'ranger',
        'faction': 'fortress',
        'hp': 594870,
        'atk': 29691,
        'armour': 1554,
        'speed': 1224,
        'hp_mult': 25,
        'atk_mult': 35,
        'control immunity': 30,
        'crit damage reduction': 25},
    'sherlock': {
        'class': 'mage',
        'faction': 'fortress',
        'hp': 591110,
        'atk': 30270,
        'armour': 1554,
        'speed': 1188,
        'hp_mult': 30,
        'atk_mult': 25,
        'damage reduction': 30},
    'unimax 3000': {
        'class': 'warrior',
        'faction': 'fortress',
        'hp': 725925,
        'atk': 21793,
        'armour': 2857,
        'speed': 1193,
        'armour_mult': 30,
        'hp_mult': 40,
        'atk_mult': 25,
        'control immunity': 30,
        'energy': 100},
    'penny': {
        'class': 'ranger',
        'faction': 'fortress',
        'hp': 565312,
        'atk': 29407,
        'armour': 1554,
        'speed': 1174,
        'hp_mult': 25,
        'atk_mult': 30,
        'crit': 30,
        'precision': 100},
    'xia': {
        'class': 'assassin',
        'faction': 'fortress',
        'hp': 488489,
        'atk': 40614,
        'armour': 1579,
        'speed': 1218,
        'atk_mult': 25,
        'crit': 35,
        'block': 70,
        'control immunity': 35},
    'valentino': {
        'class': 'mage',
        'faction': 'fortress',
        'hp': 496887,
        'atk': 27236,
        'armour': 1579,
        'speed': 1185,
        'hp_mult': 30,
        'crit': 20,
        'stun immunity': 1},
    'sigmund': {
        'class': 'warrior',
        'faction': 'fortress',
        'hp': 570590,
        'atk': 21190,
        'armour': 3171,
        'speed': 1158,
        'armour': 48,
        'atk_mult': 20,
        'hp_mult': 30,
        'precision': 30},
    'flame strike': {
        'class': 'mage',
        'faction': 'fortress',
        'hp': 711964,
        'atk': 27346,
        'armour': 1579,
        'speed': 1155,
        'hp_mult': 40,
        'atk_mult': 20,
        'crit damage': 25,
        'crit against burning': 50},
    'emily': {
        'class': 'priest',
        'faction': 'fortress',
        'hp': 558801,
        'atk': 20504,
        'armour': 1631,
        'speed': 1158,
        'hp_mult': 40},
    'ormus': {
        'class': 'priest',
        'faction': 'fortress',
        'hp': 486537,
        'atk': 26350,
        'armour': 1631,
        'speed': 1108,
        'hp_mult': 25,
        'heal effect': 50},
    'od 01': {
        'class': 'mage',
        'faction': 'fortress',
        'hp': 601879,
        'atk': 20508,
        'armour': 1631,
        'speed': 1126,
        'skill damage': 95,
        'hp_mult': 50,
        'precision': 30},
    'miki': {
        'class': 'ranger',
        'faction': 'fortress',
        'hp': 531480,
        'atk': 24387,
        'armour': 1631,
        'speed': 1200,
        'block': 40,
        'hp_mult': 25},
    'mirage': {
        'class': 'assassin',
        'faction': 'fortress',
        'hp': 529401,
        'atk': 29506,
        'armour': 1631,
        'speed': 1166,
        'block': 35,
        'atk_mult': 40},
    'bleecker': {
        'class': 'mage',
        'faction': 'fortress',
        'hp': 443460,
        'atk': 30056,
        'armour': 1579,
        'speed': 1123,
        'atk_mult': 25,
        'hp_mult': 35},
    'iceblink': {
        'class': 'ranger',
        'faction': 'fortress',
        'hp': 572933,
        'atk': 21478,
        'armour': 1709,
        'speed': 1140,
        'armour break': 40,
        'atk_mult': 30,
        'hp_mult': 25},
    'honour guard': {
        'class': 'warrior',
        'faction': 'fortress',
        'hp': 788226,
        'atk': 14301,
        'armour': 2567,
        'speed': 1152,
        'armour_mult': 48,
        'hp_mult': 40},
    'gaggie': {
        'class': 'warrior',
        'faction': 'abyss',
        'hp': 660990,
        'atk': 23241,
        'armour': 1631,
        'speed': 1172,
        'hp_mult': 40,
        'atk_mult': 20,
        'damage reduction': 30,
        'control immunity': 7},
    'aranea': {
        'class': 'priest',
        'faction': 'abyss',
        'hp': 534187,
        'atk': 28176,
        'armour': 1631,
        'speed': 1173,
        'atk_mult': 15,
        'hp_mult': 25,
        'control immunity': 15,
        'damage reduction': 25},
    'natasha': {
        'banned': True,
        'class': 'assassin',
        'faction': 'abyss',
        'hp': 579349,
        'atk': 33776,
        'armour': 1579,
        'speed': 1232,
        'hp_mult': 20,
        'atk_mult': 30,
        'crit damage': 40,
        'control immunity': 30},
    'waldeck': {
        'class': 'ranger',
        'faction': 'abyss',
        'hp': 637383,
        'atk': 26517,
        'armour': 1631,
        'speed': 1172,
        'hp_mult': 35,
        'atk_mult': 30,
        'precision': 40,
        'crit': 30,
        'control immunity': 30},
    'morax': {
        'class': 'warrior',
        'faction': 'abyss',
        'hp': 660990,
        'atk': 25178,
        'armour': 1631,
        'speed': 1172,
        'hp_mult': 40,
        'atk_mult': 30,
        'crit': 30,
        'precision': 70,
        'effect of being healed': 40},
    'ignis': {
        'class': 'priest',
        'faction': 'abyss',
        'hp': 605229,
        'atk': 24672,
        'armour': 1631,
        'speed': 1168,
        'hp_mult': 40,
        'damage reduction': 30,
        'heal effect': 25},
    'delacium': {
        'class': 'mage',
        'faction': 'abyss',
        'hp': 561999,
        'atk': 34540,
        'armour': 1631,
        'speed': 1218,
        'hp_mult': 30,
        'atk_mult': 40,
        'crit': 35,
        'control immunity': 30},
    'nakia': {
        'class': 'assassin',
        'faction': 'abyss',
        'hp': 482791,
        'atk': 35075,
        'armour': 1579,
        'speed': 1218,
        'atk_mult': 35,
        'cirt': 35,
        'control immunity': 30,
        'damage against bleeding': 80},
    'cthugha': {
        'class': 'ranger',
        'faction': 'abyss',
        'hp': 533190,
        'atk': 30564,
        'armour': 1631,
        'speed': 1145,
        'atk_mult': 25,
        'hp_mult': 20,
        'damage reduction': 20,
        'burn imunity': 1,
        'bleed immunity': 1},
    'king barton': {
        'class': 'warrior',
        'faction': 'abyss',
        'hp': 685720,
        'atk': 23998,
        'armour': 1605,
        'speed': 1158,
        'hp_mult': 40,
        'atk_mult': 35,
        'control immunity': 25,
        'damage against stunned': 100},
    'kroos': {
        'class': 'priest',
        'faction': 'abyss',
        'hp': 561999,
        'atk': 24672,
        'armour': 1631,
        'speed': 1168,
        'hp_mult': 30,
        'damage reduction': 20},
    'skerei': {
        'class': 'mage',
        'faction': 'abyss',
        'hp': 528306,
        'atk': 24273,
        'armour': 1502,
        'speed': 1153,
        'damage reduction': 20,
        'hp_mult': 35,
        'crit': 20},
    'barea': {
        'class': 'warrior',
        'faction': 'abyss',
        'hp': 772352,
        'atk': 21230,
        'armour': 2175,
        'speed': 1158,
        'hp_mult': 40,
        'atk_mult': 35,
        'armour_mult': 40},
    'dantalian': {
        'class': 'warrior',
        'faction': 'abyss',
        'hp': 691782,
        'atk': 23218,
        'armour': 2283,
        'speed': 1152,
        'armour_mult': 40,
        'atk_mult': 25,
        'hp_mult': 40,
        'damage against warrior': 70},
    'karim': {
        'class': 'assassin',
        'faction': 'abyss',
        'hp': 208443,
        'atk': 31541,
        'armour': 1554,
        'speed': 1169,
        'atk_mult': 35,
        'crit': 30,
        'hp_mult': 20},
    'gusta': {
        'class': 'warrior',
        'faction': 'abyss',
        'hp': 643759,
        'atk': 18005,
        'armour': 2283,
        'speed': 1155,
        'armour_mult': 40,
        'hp_mult': 40},
    'fat mu': {
        'class': 'ranger',
        'faction': 'abyss',
        'hp': 521999,
        'atk': 28455,
        'armour': 1554,
        'speed': 1137,
        'atk_mult': 35,
        'hp_mult': 30},
    'lord balrog': {
        'class': 'warrior',
        'faction': 'abyss',
        'hp': 752728,
        'atk': 17207,
        'armour': 2175,
        'speed': 1152,
        'armour_mult': 40,
        'hp_mult': 40},
    'queen': {
        'class': 'ranger',
        'faction': 'abyss',
        'hp': 582121,
        'atk': 33352,
        'armour': 1554,
        'speed': 1137,
        'atk_mult': 50,
        'crit damage': 30,
        'hp_mult': 25},
    'margaret': {
        'class': 'mage',
        'faction': 'abyss',
        'hp': 408090,
        'atk': 25075,
        'armour': 1502,
        'speed': 1163},
    'geester': {
        'class': 'assassin',
        'faction': 'forest',
        'hp': 570050,
        'atk': 29776,
        'armour': 1554,
        'speed': 1187,
        'hp_mult': 20,
        'atk_mult': 30,
        'crit damage': 15,
        'damage against poison': 45},
    'freya': {
        'class': 'ranger',
        'faction': 'forest',
        'hp': 568203,
        'atk': 25982,
        'armour': 1631,
        'speed': 1164,
        'atk_mult': 20,
        'hp_mult': 20,
        'crit': 20,
        'control immunity': 15},
    'xiahou': {
        'class': 'warrior',
        'faction': 'forest',
        'hp': 674231,
        'atk': 29629,
        'armour': 1579,
        'speed': 1172,
        'hp_mult': 40,
        'atk_mult': 30,
        'block': 50,
        'control immunity': 30},
    'gloria': {
        'class': 'mage',
        'faction': 'forest',
        'hp': 556808,
        'atk': 28033,
        'armour': 1579,
        'speed': 1188,
        'hp_mult': 40,
        'atk_mult': 20,
        'control immunity': 30},
    'flora': {
        'class': 'ranger',
        'faction': 'forest',
        'hp': 562949,
        'atk': 25212,
        'armour': 1554,
        'speed': 1218,
        'atk_mult': 25,
        'hp_mult': 40,
        'crit': 30},
    'rogan': {
        'banned': True,
        'class': 'assassin',
        'faction': 'forest',
        'hp': 502633,
        'atk': 26221,
        'armour': 1554,
        'speed': 1232,
        'atk_mult': 30,
        'hp_mult': 25,
        'crit damage': 40,
        'damage reduction': 30},
    'elyvia': {
        'class': 'priest',
        'faction': 'forest',
        'hp': 522739,
        'atk': 25212,
        'armour': 1554,
        'speed': 1161,
        'hp_mult': 30,
        'atk_mult': 25,
        'effect of being healed': 30},
    'garuda': {
        'class': 'warrior',
        'faction': 'forest',
        'hp': 607553,
        'atk': 25141,
        'armour': 1605,
        'speed': 1172,
        'hp_mult': 30,
        'crit damage': 40,
        'atk_mult': 25,
        'control immunity': 30},
    'oberon': {
        'class': 'mage',
        'faction': 'forest',
        'hp': 536922,
        'atk': 30369,
        'armour': 1579,
        'speed': 1188,
        'hp_mult': 35,
        'atk_mult': 30,
        'effect of being healed': 30},
    'valkyrie': {
        'class': 'ranger',
        'faction': 'forest',
        'hp': 610537,
        'atk': 25426,
        'armour': 1554,
        'speed': 1147,
        'hp_mult': 35,
        'atk_mult': 25,
        'crit': 30},
    'heart watcher': {
        'class': 'assassin',
        'faction': 'forest',
        'hp': 526084,
        'atk': 34443,
        'armour': 1554,
        'speed': 1169,
        'atk_mult': 30,
        'crit': 30,
        'hp_mult': 20},
    'vesa': {
        'class': 'priest',
        'faction': 'forest',
        'hp': 502633,
        'atk': 26221,
        'armour': 1554,
        'speed': 1116,
        'atk_mult': 30,
        'hp_mult': 25,
        'crit': 35,
        'precision': 50,
        'heal effect': 20},
    'eddga': {
        'class': 'warrior',
        'faction': 'forest',
        'hp': 472193,
        'atk': 17655,
        'armour': 1631,
        'speed': 1152},
    'rosa': {
        'class': 'priest',
        'faction': 'forest',
        'hp': 474324,
        'atk': 19360,
        'armour': 1554,
        'speed': 1132,
        'hp_mult': 40,
        'block': 35},
    'malassa': {
        'class': 'ranger',
        'faction': 'forest',
        'hp': 469515,
        'atk': 25182,
        'armour': 1554,
        'speed': 1140,
        'crit': 40,
        'atk_mult': 30},
    'groo': {
        'class': 'warrior',
        'faction': 'forest',
        'hp': 717291,
        'atk': 16351,
        'armour': 1631,
        'speed': 1158,
        'hp_mult': 44,
        'damage reduction': 26},
    'starlight': {
        'class': 'mage',
        'faction': 'forest',
        'hp': 532075,
        'atk': 32713,
        'armour': 1502,
        'speed': 1185,
        'crit': 35,
        'atk_mult': 45,
        'hp_mult': 35},
    'faceless': {
        'class': 'assassin',
        'faction': 'forest',
        'hp': 428546,
        'atk': 21643,
        'armour': 1554,
        'speed': 1166,
        'crit': 30,
        'crit damage': 50},
    'dragon slayer': {
        'class': 'warrior',
        'faction': 'forest',
        'hp': 833775,
        'atk': 15367,
        'armour': 2364,
        'speed': 1152,
        'hp_mult': 40,
        'armour_mult': 45},
    'demon hunter': {
        'class': 'ranger',
        'faction': 'forest',
        'hp': 515213,
        'atk': 24432,
        'armour': 1554,
        'speed': 1203,
        'crit': 30,
        'crit damage': 30,
        'atk_mult': 30},
    'elena': {
        'class': 'priest',
        'faction': 'dark',
        'hp': 564102,
        'atk': 28443,
        'armour': 1631,
        'speed': 1172,
        'atk_mult': 20,
        'hp_mult': 20,
        'damage reduction': 20,
        'control immunity': 10,
        'heal effect': 25},
    'mockman': {
        'class': 'warrior',
        'faction': 'dark',
        'hp': 800266,
        'atk': 23361,
        'armour': 2166,
        'speed': 1180,
        'hp_mult': 45,
        'armour_mult': 35,
        'control immunity': 25,
        'precision': 55},
    'phorcys': {
        'class': 'mage',
        'faction': 'dark',
        'hp': 571075,
        'atk': 30791,
        'armour': 1554,
        'speed': 1238,
        'hp_mult': 20,
        'atk_mult': 40,
        'skill damage': 70,
        'control immunity': 30},
    'drake': {
        'class': 'assassin',
        'faction': 'dark',
        'hp': 577606,
        'atk': 27361,
        'armour': 1554,
        'speed': 1232,
        'atk_mult': 40,
        'crit damage': 50,
        'skill damage': 70,
        'control immunity': 30,
        'dodge': 60},
    'carrie': {
        'class': 'ranger',
        'faction': 'dark',
        'hp': 551566,
        'atk': 24430,
        'armour': 1554,
        'speed': 1218,
        'atk_mult': 25,
        'control immunity': 30,
        'dodge': 40},
    'amen ra': {
        'class': 'priest',
        'faction': 'dark',
        'hp': 614426,
        'atk': 24210,
        'armour': 1579,
        'speed': 1172,
        'hp_mult': 20,
        'atk_mult': 25,
        'damage reduction': 25,
        'rounds of being controlled': -1},
    'aspen': {
        'class': 'warrior',
        'faction': 'dark',
        'hp': 716830,
        'atk': 23241,
        'armour': 1629,
        'speed': 1172,
        'hp_mult': 40,
        'atk_mult': 20,
        'crit': 35,
        'armour break': 50},
    'mihm': {
        'class': 'mage',
        'faction': 'dark',
        'hp': 569093,
        'atk': 22905,
        'armour': 1502,
        'speed': 1218,
        'hp_mult': 40,
        'damage reduction': 30,
        'control immunity': 100},
    'amuvor': {
        'class': 'assassin',
        'faction': 'dark',
        'hp': 545405,
        'atk': 35851,
        'armour': 1554,
        'speed': 1232,
        'hp_mult': 30,
        'atk_mult': 30,
        'petrify immunity': 1},
    'das moge': {
        'class': 'ranger',
        'faction': 'dark',
        'hp': 589913,
        'atk': 25407,
        'armour': 1554,
        'speed': 1145,
        'skill damage': 62.5,
        'atk_mult': 30,
        'hp_mult': 40},
    'sleepless': {
        'class': 'warrior',
        'faction': 'dark',
        'hp': 568660,
        'atk': 19368,
        'armour': 1629,
        'speed': 1160},
    'dark arthindol': {
        'class': 'mage',
        'faction': 'dark',
        'hp': 550426,
        'atk': 24045,
        'armour': 1502,
        'speed': 1188,
        'skill damage': 100,
        'hp_mult': 40},
    'yorhm tum': {
        'class': 'assassin',
        'faction': 'light',
        'hp': 585776,
        'atk': 30483,
        'armour': 1554,
        'speed': 1232,
        'hp_mult': 20,
        'atk_mult': 25,
        'control immunity': 30,
        'holy damage': 60},
    'natalie': {
        'class': 'ranger',
        'faction': 'light',
        'hp': 636602,
        'atk': 28073,
        'armour': 1555,
        'speed': 1148,
        'hp_mult': 24,
        'atk_mult': 30,
        'holy damage': 40,
        'damage reduction': 25},
    'vulcan': {
        'class': 'warrior',
        'faction': 'light',
        'hp': 714306,
        'atk': 28580,
        'armour': 1657,
        'speed': 1180,
        'atk_mult': 20,
        'hp_mult': 35,
        'holy damage': 60,
        'crit': 20,
        'control immunity': 15},
    'eos': {
        'class': 'mage',
        'faction': 'light',
        'hp': 603850,
        'atk': 23110,
        'armour': 1502,
        'speed': 1238,
        'hp_mult': 30,
        'atk_mult': 20,
        'holy damage': 30,
        'damage reduction': 30},
    'andrea': {
        'class': 'priest',
        'faction': 'light',
        'hp': 650300,
        'atk': 27236,
        'armour': 1554,
        'speed': 1172,
        'hp_mult': 40,
        'damage reduction': 30,
        'control immunity': 20,
        'heal effect': 40},
    'tussilago': {
        'class': 'assassin',
        'faction': 'light',
        'hp': 592592,
        'atk': 35406,
        'armour': 1554,
        'speed': 1232,
        'atk_mult': 30,
        'crit': 30,
        'holy damage': 80,
        'control immunity': 30},
    'russel': {
        'class': 'ranger',
        'faction': 'light',
        'hp': 513389,
        'atk': 25178,
        'armour': 1629,
        'speed': 1218,
        'atk_mult': 30,
        'holy damage': 80,
        'crit damage': 40,
        'control immunity': 30},
    'tara': {
        'class': 'warrior',
        'faction': 'light',
        'hp': 718744,
        'atk': 19368,
        'armour': 1629,
        'speed': 1172,
        'hp_mult': 40,
        'holy damage': 70,
        'control immunity': 30,
        'damage reduction': 30},
    'aida': {
        'class': 'mage',
        'faction': 'light',
        'hp': 577070,
        'atk': 29173,
        'armour': 1502,
        'speed': 1238,
        'hp_mult': 40,
        'holy damage': 100,
        'damge reduction': 30},
    'belrain': {
        'class': 'priest',
        'faction': 'light',
        'hp': 527924,
        'atk': 31891,
        'armour': 1554,
        'speed': 1132,
        'hp_mult': 30,
        'atk_mult': 45,
        'control immunity': 30,
        'heal effect': 40},
    'faith blade': {
        'class': 'assassin',
        'faction': 'light',
        'hp': 521196,
        'atk': 28724,
        'armour': 1554,
        'speed': 1232,
        'holy damage': 70,
        'crit': 30,
        'stun immunity': 1},
    'michelle': {
        'class': 'ranger',
        'faction': 'light',
        'hp': 613850,
        'atk': 19544,
        'armour': 1554,
        'speed': 1188,
        'holy damage': 60,
        'hp_mult': 60,
        'control immunity': 100},
    'asmodel': {
        'class': 'warrior',
        'faction': 'light',
        'hp': 746425,
        'atk': 25389,
        'armour': 1605,
        'speed': 1172,
        'hp_mult': 40,
        'atk_mult': 35,
        'holy damage': 50,
        'crit': 35,
        'control immunity': 30},
    'gerke': {
        'class': 'priest',
        'faction': 'light',
        'hp': 587486,
        'atk': 23501,
        'armour': 1554,
        'speed': 1108,
        'holy damage': 60,
        'atk_mult': 25,
        'hp_mult': 20,
        'crit': 20},
}
